"""Add policy number column

Revision ID: 485a0ffff5b4
Revises: 5aba4d45913a
Create Date: 2026-01-21 23:54:44.779921

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "485a0ffff5b4"
down_revision: Union[str, Sequence[str], None] = "5aba4d45913a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("policy_number", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.drop_column("policy_number")

    # ### end Alembic commands ###
