"""Perpetual Policies

Revision ID: 5aba4d45913a
Revises: af0b725baabc
Create Date: 2026-01-19 14:06:20.995024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aba4d45913a'
down_revision: Union[str, Sequence[str], None] = 'af0b725baabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
